@startuml

skinparam monochrome true

package "Utilitaires" <<Rectangle>> {
}

package "Réseau" <<Rectangle>> {
}

package "Sessions" <<Rectangle>> {
}

package "Contrôleur" <<Rectangle>> {
}

package "Système de fichiers" <<Rectangle>> {
}

package "Base de données" <<Rectangle>> {
}

package "Interface graphique" <<Rectangle>> {
}

package "Médias" <<Rectangle>> {
}

"Réseau" -- "Contrôleur"

"Contrôleur" -- "Sessions"

"Contrôleur" -- "Base de données"

"Contrôleur" -- "Utilitaires"

"Contrôleur" -- "Système de fichiers"

"Contrôleur" -- "Interface graphique"

"Contrôleur" -- "Médias"

@enduml
