@startuml


class FileManager{
- final Logger LOG
- static FileManager instance
+ Static OUTPUT_DIRECTORY

-FileManager()
+FileManager getInstance()
+File retrieveFile(InputStream inputStream, int fileSize)
+String getFormatExtension(File file)
+byte[] getBytes(File file, int nbBytes)
+void delete(File fileToDelete)
+void rename(File file, File newFilename)
+String getMD5Checksum(File file)
}

class FilesFormats{

+final byte[] MP3_HEADER
+final int MP3_HEADER_OFFSET
+final String MP3_EXTENSION
+final byte[] M4A_HEADER
+final int M4A_HEADER_OFFSET
+final String M4A_EXTENSION
+ final byte[] WAV_HEADER
+final int WAV_HEADER_OFFSET
+final String WAV_EXTENSION

}




@enduml
