@startuml


Client -> Client : Format\nsupporté ?

Client -> Serveur : Envoi des métadonnées\n(titre, artiste, album, durée, format, taille)

Serveur -> Serveur: Format\nsupporté ?

Client <--x Serveur : <i>Format non supporté</i>

Serveur -> Serveur : Chanson déjà\nprésente dans la\nbase de données ?

Client <--x Serveur : <i>Chanson déjà présente</i>

Serveur -> Serveur : Combien d'uploads\nactifs?

Client <--x Serveur : <i>Trop d'uploads actifs</i>

Serveur -> Serveur : Espace disque\nsuffisant?

Client <--x Serveur : : <i>Espace disque insuffisant</i>

Serveur -> Serveur : Réservation de\nl'espace disque

Client <-- Serveur : <i>OK pour le transfert</i>

Client -> Serveur : Envoi de la chanson

Serveur -> Serveur : Erreur lors du\ntransfert?

Client <--x Serveur : <i>Erreur lors du transfert</i>

Serveur -> Serveur : Ajout à la base\nde données

Client <-- Serveur : Transfert réussi

Serveur -> Serveur : Mise à jour\nde la capactié\nde l'espace disque

@enduml
