@startuml

class Player {
    -String name

    +play()
    +stop()
    +pause()

    +next()
    +previous()
}

class Playlist {
    -String name

    +setName()
    +getName()

    +addTrack()
    +removeTrack()
    +deleteTrack()

    +getTrack()
    +getTracks()

}

class Track {
    -String artist
    -String title
    -String album
    -String duration
    -String uri
    -Timestamp addedDate
    -Timestamp playedDate

    +getArtist()
    +getTitle()
    +getAlbum()
    +getDuration()
    +getUri()
    +getAddedDate()
    +getPlayedDate()
}

class PlaylistManager {
    -ArrayList<Playlist>
}

class VoteManager {
    -Track track
    -Playlist playlist
    -int votes

    +getVote()
    +updateVote()
}


class StorageManager {

    +store(Track)
    +remove(Track)
    +clean()

}

class NetworkManager {

    -broadcast()
}


Player <..> Playlist

Track <..> VoteManager

VoteManager <..> Playlist

StorageManager <..> Playlist

Playlist <..> PlaylistManager

NetworkManager <..> StorageManager

@enduml
