@startuml
start

repeat
repeat

:Lecture d'une ligne;

:Ajout de la ligne au tableau de la commande;

repeat while (NOT END_OF_COMMAND ou\n NOT socket fermé)

if (socket a été fermé?) then (oui)
    :Ajout de la commande
 END_OF_COMMUNICATION
 et de l'id;
endif

:Défini la commande à
envoyer comme étant
la première cellule du tableau
de la commande;

:Défini les arguments de la commande
comme étant le reste du tableau de la
commande;

:Ajoute le socket aux arguments;

:Demande au Core d'executer la
commande et récupère le résultat;

if (résultat = END_OF_COMMUNICATION
OU résultat = chaine vide?)

else (non)
    :Envoie du résultat;

endif

repeat while (la commande envoyée n'est
pas END_OF_COMMUNICATION)


stop
@enduml
