@startuml

    namespace ch.tofind.commusica {

        class Commusica {
            [[Commusica.html]]
            {static} -LOG: Logger
            {static} +main(String[]): void
        }

    }

@enduml
