@startuml

skinparam objectAttributeIconSize 0

object Configuration

object NetworkManager

object SessionManager

object Session

object Controller

object FileManager

object DatabaseManager

object PlaylistManager

object Playlist

object Player

object Track

NetworkManager -- Controller

NetworkManager -- SessionManager

SessionManager -- Session

Controller -- FileManager
Controller -- DatabaseManager
Controller -- PlaylistManager

PlaylistManager -- Playlist

Playlist -- Player
Playlist -- Track

note left of Configuration
    Permet de charger la
    configuration depuis
    un fichier texte
endnote

note left of NetworkManager
    Communication entre
    le serveur et le client
endnote

note left of SessionManager
    Permet de gérer les
    différents utilisateurs
endnote

note left of Session
    Abstraction d'une
    session utilisateur
endnote

note left of Controller
    "Routeur" qui rédirige
    les demandes du client
endnote

note left of FileManager
    Gestionnaire de
    fichiers au niveau
    du système hôte
endnote

note left of DatabaseManager
    Interraction avec
    la base de données
endnote

note left of PlaylistManager
    Gestionnaire
    de playlists

endnote

note left of Playlist
    Abstraction
    d'une playlist
endnote

note left of Player
    Lecture
    de musique
endnote

note left of Track
    Abstraction
    d'une chanson
endnote

@enduml
